name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: PreparedStatementInjectionTest
      id: preparedstatementinjectiontest
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: PreparedStatementInjectionTest
        setup-command: ''
        command: gradle -q test --tests com.example.project.PreparedStatementInjectionTest
        timeout: 3
        max-score: 1
    - name: TransactionRollbackTest
      id: transactionrollbacktest
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: TransactionRollbackTest
        setup-command: ''
        command: gradle -q test --tests com.example.project.TransactionRollbackTest
        timeout: 3
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PREPAREDSTATEMENTINJECTIONTEST_RESULTS: "${{steps.preparedstatementinjectiontest.outputs.result}}"
        TRANSACTIONROLLBACKTEST_RESULTS: "${{steps.transactionrollbacktest.outputs.result}}"
      with:
        runners: preparedstatementinjectiontest,transactionrollbacktest
